### ISSUE TITLE
TypeScript declarations broken in 9.0.4

### ISSUE THREAD

**Issue by grzegorzjudas** [ipfs/js-ipfs-utils#169]
Hello,

after recent clean install of project dependencies (after removal of package-lock) we stumbled upon a build failure:
```
node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:10:14 - error TS2503: Cannot find namespace 'fs'.

10     content: fs.ReadStream | undefined;
```
After examining the contents of that file, it looks like the `fs` has no reference. It worked in 9.0.2, so I downgraded and found that there's a missing part at the top:
```
/// <reference types="node" />
```
that causes the build to fail.

I'm not too sure what changed between the versions, but the downgrade definitely did the trick.

**Comment by raress96** [comment]
Hello, I also have this same problem
`Cannot find namespace 'fs'`

Waiting for a fix, until then will downgrade I guess.

**Comment by JAGDISH0008** [comment]
> Hello, I also have this same problem `Cannot find namespace 'fs'`
> 
> Waiting for a fix, until then will downgrade I guess.

To which version we should downgrade.?

**Comment by raress96** [comment]
> > Hello, I also have this same problem `Cannot find namespace 'fs'`
> > Waiting for a fix, until then will downgrade I guess.
> 
> To which version we should downgrade.?

I downgraded to 9.0.2 and it works fine.

**Comment by H3xept** [comment]
Bump, this is still an issue. 

node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:10:14 - error TS2503: Cannot find namespace 'fs'.

10     content: fs.ReadStream | undefined;
                ~~


Found 1 error in node_modules/ipfs-utils/dist/src/files/glob-source.d.ts:10
